[tool]
[tool.poetry]
authors = ["Your Name <you@example.com>"]
name = "root"
version = "0.0.0"
[tool.poetry.dependencies]
flask = "==1.1.1"
flask-ext = "==0.1"
flask-login = "==0.4.1"
python = "^3.7"
sqlalchemy-nuodb = "==2.3.1"
wtforms = "^2.2"
selenium = "^3.141"
